// Generated by CoffeeScript 1.10.0

/*  
  default behavior: log chat logs to file
  @command top (count) (chat-lines): show group's chat ranks in (count) depends on recently (chat-lines) history.
  need configs:
  -
 */

(function() {
  module.exports = function(content, send, robot, message) {
    return "nothing";
  };

}).call(this);
